# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gu5MmlNV5jGXg0IezNz4IKe4kLkjmwEZ
"""

import streamlit as st
import numpy as np
import pickle

model = pickle.load(open('heart_model.pkl', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))

st.set_page_config(page_title="Heart Disease Risk Assessment", layout="centered")

st.title("🫀 Heart Disease Risk Assessment")
st.write("Enter your health details to assess the risk of heart disease.")

age = st.number_input("Age", min_value=1, max_value=120, value=30)

sex = st.selectbox("Sex", ("Male", "Female"))
sex = 1 if sex == "Male" else 0

cp = st.selectbox(
    "Chest Pain Type",
    ("Typical Angina", "Atypical Angina", "Non-anginal Pain", "Asymptomatic")
)
cp = ["Typical Angina", "Atypical Angina", "Non-anginal Pain", "Asymptomatic"].index(cp)

trestbps = st.number_input("Resting Blood Pressure (mm Hg)", value=120)
chol = st.number_input("Serum Cholesterol (mg/dl)", value=200)

fbs = st.selectbox("Fasting Blood Sugar > 120 mg/dl", ("No", "Yes"))
fbs = 1 if fbs == "Yes" else 0

restecg = st.selectbox("Resting ECG Results", (0, 1, 2))
thalach = st.number_input("Maximum Heart Rate Achieved", value=150)

exang = st.selectbox("Exercise Induced Angina", ("No", "Yes"))
exang = 1 if exang == "Yes" else 0

oldpeak = st.number_input("ST Depression (Oldpeak)", value=1.0)

slope = st.selectbox("Slope of Peak Exercise ST Segment", (0, 1, 2))
ca = st.selectbox("Number of Major Vessels (0–3)", (0, 1, 2, 3))

thal = st.selectbox("Thalassemia", ("Normal", "Fixed Defect", "Reversible Defect"))
thal = ["Normal", "Fixed Defect", "Reversible Defect"].index(thal)

if st.button("🔍 Predict Heart Disease Risk"):
    input_data = np.array([[
        age, sex, cp, trestbps, chol, fbs,
        restecg, thalach, exang, oldpeak,
        slope, ca, thal
    ]])

    input_scaled = scaler.transform(input_data)
    prediction = model.predict(input_scaled)

    if prediction[0] == 1:
        st.error("⚠️ High Risk of Heart Disease")
    else:
        st.success("✅ Low Risk of Heart Disease")